export CUDA_VISIBLE_DEVICES=0

python -u run.py \
  --is_training 1 \
  --lradj 'TST' \
  --patience 3 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96 \
  --model $1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 1 \
  --d_model 32 \
  --d_ff 32 \
  --learning_rate 0.02 \
  --batch_size 256 \
  --fix_seed 2025 \
  --use_norm 1 \
  --wv db1 \
  --m 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des Exp \
  --itr $2 \
  --alpha 0.3 \
  --l1_weight 0.0005 \
  --topk_ratio 0.1 \
  --dropout_alpha 0.5 \
  --dropout_data 0.5

python -u run.py \
  --is_training 1 \
  --lradj 'TST' \
  --patience 3 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96 \
  --model $1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 1 \
  --d_model 32 \
  --d_ff 32 \
  --learning_rate 0.02 \
  --batch_size 256 \
  --fix_seed 2025 \
  --use_norm 1 \
  --wv db1 \
  --m 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des Exp \
  --itr $2 \
  --alpha 0.3 \
  --l1_weight 0.0005 \
  --topk_ratio 0.1 \
  --dropout_alpha 0.9 \
  --dropout_data 0.1

python -u run.py \
  --is_training 1 \
  --lradj 'TST' \
  --patience 3 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96 \
  --model $1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 1 \
  --d_model 32 \
  --d_ff 32 \
  --learning_rate 0.02 \
  --batch_size 256 \
  --fix_seed 2025 \
  --use_norm 1 \
  --wv db1 \
  --m 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des Exp \
  --itr $2 \
  --alpha 0.3 \
  --l1_weight 0.0005 \
  --topk_ratio 0.1 \
  --dropout_alpha 0.9 \
  --dropout_data 0.1

python -u run.py \
  --is_training 1 \
  --lradj 'TST' \
  --patience 3 \
  --root_path ./dataset/exchange_rate/ \
  --data_path exchange_rate.csv \
  --model_id Exchange_96_96 \
  --model $1 \
  --data custom \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 1 \
  --d_model 32 \
  --d_ff 32 \
  --learning_rate 0.02 \
  --batch_size 256 \
  --fix_seed 2025 \
  --use_norm 1 \
  --wv db1 \
  --m 3 \
  --enc_in 8 \
  --dec_in 8 \
  --c_out 8 \
  --des Exp \
  --itr $2 \
  --alpha 0.3 \
  --l1_weight 0.0005 \
  --topk_ratio 0.1 \
  --dropout_alpha 0.9 \
  --dropout_data 0.1